export const majors = [
    "Accounting and Information Systems",
    "Advertising",
    "Aerospace Engineering",
    "Agribusiness",
    "Agricultural Sciences",
    "Agricultural Technology (Associate Degree)",
    "Animal and Poultry Sciences",
    "Arabic",
    "Architecture",
    "Art History",
    "Biochemistry",
    "Biological Sciences (Biology)",
    "Biological Systems Engineering",
    "Biomedical Engineering",
    "Building Construction",
    "Business (undecided)",
    "Business Information Technology",
    "Career and Technical Education",
    "Career and Technical Education - Agriculture Education",
    "Chemical Engineering",
    "Chemistry",
    "Cinema",
    "Civil Engineering",
    "Classical Studies",
    "Clinical Neuroscience",
    "Cognitive and Behavioral Neuroscience",
    "Communication",
    "Community Economic Development",
    "Computational Modeling and Data Analytics",
    "Computational and Systems Neuroscience",
    "Computer Engineering",
    "Computer Science",
    "Construction Engineering and Management",
    "Consumer Studies",
    "Creative Technologies",
    "Creative Writing",
    "Criminology",
    "Crop and Soil Sciences",
    "Cybersecurity Management and Analytics",
    "Dairy Science",
    "EUropean and Transatlantic Studies",
    "Early Childhood Development and Education",
    "Ecological Restoration",
    "Economics",
    "Electrical Engineering",
    "Elementary Education (PK-6)",
    "English",
    "English Language Arts Education",
    "Entrepreneurship, Innovation and Technology Management",
    "Environmental Conservation and Society",
    "Environmental Data Science",
    "Environmental Economics: Management and Policy",
    "Environmental Horticulture",
    "Environmental Policy and Planning",
    "Environmental Resources Management",
    "Environmental Science",
    "Exercise & Health Sciences",
    "Experimental Neuroscience",
    "Explore Liberal Arts and Human Sciences (Undecided)",
    "Explore Science (undecided)",
    "Exploring Architecture, Arts, and Design (undecided)",
    "Exploring Life Sciences (undecided)",
    "Exploring Natural Resources (undecided)",
    "Fashion Merchandising and Design",
    "FinTech and Big Data Analytics",
    "Finance",
    "Finance and Real Estate",
    "Financial Planning and Wealth Management",
    "Fish Conservation",
    "Food Science and Technology",
    "Food and Health Systems Economics",
    "Forestry",
    "French",
    "General Engineering",
    "Geography",
    "Geosciences",
    "German",
    "Graphic Design",
    "History",
    "History and Social Sciences Education",
    "Hospitality and Tourism Management",
    "Human Development",
    "Human Nutrition, Foods, and Exercise",
    "Human Resource Management",
    "Humanities for Public Service",
    "Industrial Design",
    "Industrial and Systems Engineering",
    "Integrated Agriculture Technologies",
    "Interior Design",
    "International Public Policy",
    "International Relations",
    "International Studies",
    "International Trade and Development",
    "Landscape Architecture",
    "Landscape Design and Turfgrass Science",
    "Management",
    "Management Consulting and Analytics",
    "Marketing Management",
    "Materials Science and Engineering",
    "Mathematics",
    "Mathematics Education",
    "Mechanical Engineering",
    "Medicinal Chemistry",
    "Meteorology",
    "Microbiology",
    "Mining Engineering",
    "Multimedia Journalism",
    "Music",
    "Nanomedicine",
    "Nanoscience",
    "National Security and Foreign Affairs",
    "Nutrition and Dietetics",
    "Ocean Engineering",
    "Packaging Systems and Design",
    "Philosophy",
    "Philosophy, Politics, and Economics",
    "Physics",
    "Plant Science",
    "Political Science",
    "Polymer Chemistry",
    "Pre-Education",
    "Pre-Health Professions",
    "Pre-Law",
    "Pre-Medicine",
    "Pre-Veterinary Medicine",
    "Professional and Technical Writing",
    "Property Management",
    "Psychology",
    "Public Health",
    "Public Relations",
    "Real Estate for Commercial Properties",
    "Real Estate for Residential Properties",
    "Religion and Culture",
    "Residential Environments and Design",
    "Russian",
    "Smart and Sustainable Cities",
    "Sociology",
    "Spanish",
    "Sports Media and Analytics",
    "Statistics",
    "Studio Art",
    "Sustainable Biomaterials",
    "Systems Biology",
    "Theatre Arts",
    "University Studies (undecided)",
    "Water: Resources, Policy, and Management",
    "Wildlife Conservation"
];

export const months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
];
